server:
  servlet:
    context-path: /showing
    encoding:
      charset: UTF-8
      enabled: true
      
spring:
  datasource:
    url: jdbc:mysql://bookingdb.cfopqpmerg9j.us-west-1.rds.amazonaws.com:3306/booking_project_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: CK220809
    driver-class-name: com.mysql.cj.jdbc.Driver